name: charuconstruction_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logging: ^1.3.0
  collection: ^1.19.1
  path_provider: ^2.1.5
  advance_math: ^5.5.3
  universal_ble: ^1.2.0
  opencv_dart: ^2.2.2
  dartcv4: ^2.2.2
  fl_chart: ^1.2.0
  camera: ^0.12.0+1

dependency_overrides: 
  opencv_dart: 
    path: ../external/opencv_dart/packages/opencv_dart
  dartcv4: 
    path: ../external/opencv_dart/packages/dartcv

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/charucos/charuco_4x6_24/board.json
    - assets/charucos/charuco_4x6_42/board.json

hooks:
  user_defines:
    dartcv4:
      include_modules: 
        - calib3d
        - contrib
        - dnn
        - features2d
        - freetype
        - highgui
        - imgcodecs
        - imgproc
        - objdetect
        - photo
        - stitching
        - video
        - videoio
        - aruco
        - img_hash
        - quality
        - wechat_qrcode
        - ximgproc
        - xobjdetect
